[package]
name = "idrive_backup"
version = "0.1.0"
authors = ["Adam Reichold <adam.reichold@t-online.de>"]
edition = "2018"

[dependencies]
chrono = "0.4"
tempfile = "3.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde-xml-rs = { version = "0.3", default-features = false }

[profile.release]
opt-level = "s"
lto = true
